<?php

namespace App\Foorm\ApiCandidato;


use App\Foorm\Candidato\Actions\XlsExportTrait;
use App\Foorm\Evento\EventoTrait;
use Gecche\Cupparis\App\Foorm\Base\FoormList as BaseFoormList;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class FoormList extends BaseFoormList
{

    use XlsExportTrait;

    protected $excelDates = false;

    protected $separator = ";";
    protected $separatorReplacer = ',';

    protected $fields = [

        "iniziativa_id",
        "cognome",
        "nome",
        "codice_fiscale",
        "data_candidatura",
        "sesso",
        "luogo_nascita",
        "data_nascita",
        "indirizzo",
        "cap",
        "comune",
        "comune_catastale",
        "provincia_id",
        "regione_id",
        "nazione_id",
        "telefono",
        "emails",

        "gen1_titolo_studio_id",
        "gen2_titolo_studio_id",

        "scuola|tipologia_grado_istruzione",
        "classe",
        "scuola|regione_id",

        "scuola|biennio",
        "scuola|denominazione",
        "scuola_estera",
        "scuola|email_riferimento",
        "profilo",


        'olimpiadi_matematica',
        'olimpiadi_matematica_squadre',
        'olimpiadi_matematica_squadre_femminili',
        'olimpiadi_fisica',
        'olimpiadi_fisica_squadre_miste',
        'olimpiadi_scienze_naturali',
        'giochi_chimica',
        'olimpiadi_informatica',

        'stages',
        'gare_internazionali',
        'gare_umanistiche',
        'partecipazione_concorsi',

        'inglese_livello_linguistico_id',
        'francese_livello_linguistico_id',
        'spagnolo_livello_linguistico_id',
        'tedesco_livello_linguistico_id',
        'cinese_livello_linguistico_id',

        'altre_competenze_linguistiche',

        'esperienze_estere',
        'materie_preferite',
        'settore_professionale',
        'motivazioni',

        'corsi',

        'media',
        'status',
        'voti',

    ];

    protected $iniziativaId;

    protected function init()
    {
        $this->iniziativaId = Arr::get($this->params,'iniziativa_id',false);
    }


    protected function applyListBuilder()
    {
        $modelClass = get_class($this->model);
        $this->formBuilder = $modelClass::query(); // TODO: Change the autogenerated stub
    }

    public function getDataFromBuilder($params = [])
    {


        if ($this->iniziativaId !== false) {
            parent::getDataFromBuilder($params);
            return;
        }



        $items = $this->formBuilder->get();


        $data = [];
        $headersArray = $this->getCsvRowHeaders();
        $headersArray = Arr::prepend($headersArray, "Iniziativa");
        foreach ($items as $item) {
            $valuesArray = $this->getCsvRow($item);
//            Log::info("VALORI");
//            Log::info($valuesArray);
            $headersRowArray = array_slice($headersArray, 0, count($valuesArray));
            $data[] = array_combine($headersRowArray, $valuesArray);
        }

        $this->formData = $data;
    }


    public function getCsvRow($item)
    {
        $row = [];
        $itemArray = $item->toArray();
        $itemDotted = Arr::dot($itemArray);
        foreach ($this->fields as $key) {
            $methodKey = str_replace('|', '', $key);

            $itemValue = $this->guessItemValue($key, $itemDotted, $itemArray, $item);

//            Log::info("FIELD:::");
//            Log::info($key);

            $methodName = 'getCsvField' . Str::studly($methodKey);
            if (method_exists($this, $methodName)) {
                $field = $this->$methodName($itemValue, $itemArray, $item);
                if (is_array($field)) {
                    foreach ($field as $currfield) {
                        $row[] = $currfield;
                    }
                } else {
                    $row[] = $field;
                }
//                Log::info("VALUE:::");
//                Log::info($field);
            } else {
                $row[] = $this->getCsvFieldStandard($key, $itemValue, $itemArray, $item);
            }
//            Log::info("ROW:::");
//            Log::info($row);
        }
        return $row;
    }


    public function getCsvFieldStandard($key, $value, $item = [], $itemObject = null)
    {
//        if (is_numeric($value)) {
//            if ($this->csvSettings['decimalTo']) {
//                $value = str_replace($this->csvSettings['decimalFrom'],
//                    $this->csvSettings['decimalTo'],
//                    $value);
//            }
//        } else {
        $value = str_replace(['"', "'", "\n", "\r"], '', $value);
        $value = str_replace($this->separator, $this->separatorReplacer, $value);
//        }
        return $value;

    }


    protected function guessItemValue($key, $itemDotted, $item, $itemObject)
    {

        $fieldKey = str_replace('|', '.', $key);
        $itemValue = Arr::get($itemDotted, $fieldKey);
        if (!$itemValue && array_key_exists($key, $item) && is_array($item[$key])) {
            $itemValue = $item[$key];
        }

        return $itemValue;
    }

    protected function getCsvFieldIniziativaId($value, $itemArray, $item)
    {
        return $item->iniziativa->titolo;
    }

    protected function getCsvFieldDataNascita($value)
    {
        return $value;
    }

    protected function getCsvFieldDataCandidatura($value)
    {
        return $value;
    }
}

