<?php

namespace App\Foorm\ApiFaq;


use App\Foorm\Candidato\Actions\XlsExportTrait;
use App\Foorm\Evento\EventoTrait;
use Gecche\Cupparis\App\Foorm\Base\FoormList as BaseFoormList;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class FoormList extends BaseFoormList
{


    protected function applyListBuilder()
    {
        $modelClass = get_class($this->model);
        $this->formBuilder = $modelClass::query(); // TODO: Change the autogenerated stub
    }


}

