<?php

namespace App\Foorm\ApiIniziativa;


use App\Foorm\Candidato\Actions\XlsExportTrait;
use App\Foorm\Evento\EventoTrait;
use Gecche\Cupparis\App\Foorm\Base\FoormList as BaseFoormList;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class FoormList extends BaseFoormList
{

    protected $excelDates = false;

    protected $separator = ";";
    protected $separatorReplacer = ',';

    protected $fields = [

        "iniziativa_id",
        "cognome",
        "nome",
        "codice_fiscale",
        "data_candidatura",
        "sesso",
        "luogo_nascita",
        "data_nascita",
        "indirizzo",
        "cap",
        "comune",
        "comune_catastale",
        "provincia_id",
        "regione_id",
        "nazione_id",
        "telefono",
        "emails",

        "gen1_titolo_studio_id",
        "gen2_titolo_studio_id",

        "scuola|tipologia_grado_istruzione",
        "classe",
        "scuola|regione_id",

        "scuola|biennio",
        "scuola|denominazione",
        "scuola_estera",
        "scuola|email_riferimento",
        "profilo",


        'olimpiadi_matematica',
        'olimpiadi_matematica_squadre',
        'olimpiadi_matematica_squadre_femminili',
        'olimpiadi_fisica',
        'olimpiadi_fisica_squadre_miste',
        'olimpiadi_scienze_naturali',
        'giochi_chimica',
        'olimpiadi_informatica',

        'stages',
        'gare_internazionali',
        'gare_umanistiche',
        'partecipazione_concorsi',

        'inglese_livello_linguistico_id',
        'francese_livello_linguistico_id',
        'spagnolo_livello_linguistico_id',
        'tedesco_livello_linguistico_id',
        'cinese_livello_linguistico_id',

        'altre_competenze_linguistiche',

        'esperienze_estere',
        'materie_preferite',
        'settore_professionale',
        'motivazioni',

        'corsi',

        'media',
        'status',
        'voti',

    ];

    protected function applyListBuilder()
    {
        $modelClass = get_class($this->model);
        $this->formBuilder = $modelClass::query(); // TODO: Change the autogenerated stub
    }
//
//    public function getDataFromBuilder($params = [])
//    {
//
//
//        $items = $this->formBuilder->get();
//
//
//        $data = [];
//        $headersArray = $this->getCsvRowHeaders();
//        $headersArray = Arr::prepend($headersArray, "Iniziativa");
//        foreach ($items as $item) {
//            $valuesArray = $this->getCsvRow($item);
////            Log::info("VALORI");
////            Log::info($valuesArray);
//            $headersRowArray = array_slice($headersArray, 0, count($valuesArray));
//            $data[] = array_combine($headersRowArray, $valuesArray);
//        }
//
//        $this->formData = $data;
//    }


}

