@include('candidature.form.riepilogo-text',['value' => $candidatura->inglese->nome,'label' => 'Inglese'])
@include('candidature.form.riepilogo-text',['value' => $candidatura->francese->nome,'label' => 'Francese'])
@include('candidature.form.riepilogo-text',['value' => $candidatura->tedesco->nome,'label' => 'Tedesco'])
@include('candidature.form.riepilogo-text',['value' => $candidatura->spagnolo->nome,'label' => 'Spagnolo'])
@include('candidature.form.riepilogo-text',['value' => $candidatura->cinese->nome,'label' => 'Cinese'])
@include('candidature.form.riepilogo-text',['value' => $candidatura->altre_competenze_linguistiche,'label' => 'Altro'])
