<?php

namespace App\Models;

use Gecche\Cupparis\App\Breeze\Breeze;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Support\Str;

/**
 * Breeze (Eloquent) model for classi table.
 */
class Classe extends Breeze
{
    use Relations\ClasseRelations;
    use HasSlug;


    //    use ModelWithUploadsTrait;

    protected $table = 'classi';

    //protected $fillable = [];

    public $timestamps = true;
    public $ownerships = true;

    public $appends = [];


    public static $relationsData = [

        'materie' => [self::HAS_MANY, 'related' => Classe::class, 'table' => 'materie_orientamento', 'foreignKey' => 'classe_id'],


        //        'belongsto' => array(self::BELONGS_TO, Classe::class, 'foreignKey' => '<FOREIGNKEYNAME>'),
        //        'belongstomany' => array(self::BELONGS_TO_MANY, Classe::class, 'table' => '<TABLEPIVOTNAME>','pivotKeys' => [],'foreignKey' => '<FOREIGNKEYNAME>','otherKey' => '<OTHERKEYNAME>') ,
        //        'hasmany' => array(self::HAS_MANY, Classe::class, 'table' => '<TABLENAME>','foreignKey' => '<FOREIGNKEYNAME>'),
    ];

    public static $rules = [
        //        'username' => 'required|between:4,255|unique:users,username',
    ];

    public $columnsForSelectList = ['nome_it'];
    //['id','descrizione'];

    public $defaultOrderColumns = ['nome_it' => 'ASC',];
    //['cognome' => 'ASC','nome' => 'ASC'];

    public $columnsSearchAutoComplete = ['nome_it'];
    //['cognome','denominazione','codicefiscale','partitaiva'];

    public $nItemsAutoComplete = 20;
    public $nItemsForSelectList = 100;
    public $itemNoneForSelectList = false;
    public $fieldsSeparator = ' - ';

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom(['nome_it'])
            ->saveSlugsTo('slug_it');
    }
    public function getRouteKeyName()
    {
        return 'slug_it';
    }

    public function save(array $options = [])
    {

        try {
            $saved = parent::save($options); // TODO: Change the autogenerated stub
        } catch (\Throwable $e) {
            if (Str::contains($e->getMessage(), "classi_nome_it_unique")) {
                throw new \Exception("Le classi devono avere dei titoli univoci.");
            }
        }
        return $saved;
    }
}
