<?php

namespace App\Models;

use Gecche\Cupparis\App\Breeze\Breeze;

/**
 * Breeze (Eloquent) model for comuni table.
 */
class Comune extends Breeze
{
	use Relations\ComuneRelations;


    
//    use ModelWithUploadsTrait;

    protected $table = 'comuni';

    //protected $fillable = [];

    public $timestamps = true;
    public $ownerships = true;

    public $appends = [

    ];


    public static $relationsData = [

			'provincia' => [self::BELONGS_TO, 'related' => 'App\Models\Provincia', 'table' => 'province', 'foreignKey' => 'provincia_id'],
			'regione' => [self::BELONGS_TO, 'related' => 'App\Models\Regione', 'table' => 'regioni', 'foreignKey' => 'regione_id'],
			'nazione' => [self::BELONGS_TO, 'related' => 'App\Models\Nazione', 'table' => 'nazioni', 'foreignKey' => 'nazione_id'],


//        'belongsto' => array(self::BELONGS_TO, Comune::class, 'foreignKey' => '<FOREIGNKEYNAME>'),
//        'belongstomany' => array(self::BELONGS_TO_MANY, Comune::class, 'table' => '<TABLEPIVOTNAME>','pivotKeys' => [],'foreignKey' => '<FOREIGNKEYNAME>','otherKey' => '<OTHERKEYNAME>') ,
//        'hasmany' => array(self::HAS_MANY, Comune::class, 'table' => '<TABLENAME>','foreignKey' => '<FOREIGNKEYNAME>'),
    ];

    public static $rules = [
//        'username' => 'required|between:4,255|unique:users,username',
    ];

    public $columnsForSelectList = ['nome'];
     //['id','descrizione'];

    public $defaultOrderColumns = ['nome' => 'ASC', ];
     //['cognome' => 'ASC','nome' => 'ASC'];

    public $columnsSearchAutoComplete = ['nome', 'codice_catastale'];
     //['cognome','denominazione','codicefiscale','partitaiva'];

    public $nItemsAutoComplete = 20;
    public $nItemsForSelectList = 100;
    public $itemNoneForSelectList = false;
    public $fieldsSeparator = ' - ';

    public function save(array $options = [])
    {
        if ($this->provincia_id) {
            $provincia = Provincia::where('id', $this->provincia_id)->first();
            $this->regione_id = $provincia->regione_id;
        } else {
            $this->regione_id = null;
        }

        $this->nazione_id = 1;

        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
