<?php

namespace App\Models;

use App\Services\FormatValues;
use Carbon\Carbon;
use Gecche\Cupparis\App\Breeze\Breeze;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

/**
 * Breeze (Eloquent) model for corsi table.
 */
class Corso extends Breeze
{
	use Relations\CorsoRelations;

    use HasSlug;


//    use ModelWithUploadsTrait;

    protected $table = 'corsi';

    //protected $fillable = [];

    public $timestamps = true;
    public $ownerships = true;

    public $appends = [

    ];


    public static $relationsData = [

			'provincia' => [self::BELONGS_TO, 'related' => 'App\Models\Provincia', 'table' => 'province', 'foreignKey' => 'provincia_id'],
			'iniziativa' => [self::BELONGS_TO, 'related' => 'App\Models\Iniziativa', 'table' => 'iniziative', 'foreignKey' => 'iniziativa_id'],
        'candidati' => [self::BELONGS_TO_MANY, 'related' => Candidato::class, 'table' => 'candidati_corsi', 'pivotFields' => ['ordine'], 'foreignPivotKey' => 'corso_id', 'relatedPivotKey' => 'candidato_id'],


        'fotos' => [self::MORPH_MANY, 'related' => Foto::class, 'name' => 'mediable'],
        'attachments' => [self::MORPH_MANY, 'related' => Attachment::class, 'name' => 'mediable'],

//        'belongsto' => array(self::BELONGS_TO, Iniziativa::class, 'foreignKey' => '<FOREIGNKEYNAME>'),
//        'belongstomany' => array(self::BELONGS_TO_MANY, Iniziativa::class, 'table' => '<TABLEPIVOTNAME>','pivotKeys' => [],'foreignKey' => '<FOREIGNKEYNAME>','otherKey' => '<OTHERKEYNAME>') ,
//        'hasmany' => array(self::HAS_MANY, Iniziativa::class, 'table' => '<TABLENAME>','foreignKey' => '<FOREIGNKEYNAME>'),
    ];

    public static $rules = [
        'titolo' => 'required',
        'iniziativa_id' => 'required',

//        'username' => 'required|between:4,255|unique:users,username',
    ];

    public $columnsForSelectList = ['titolo','luogo','data_inizio','data_fine'];
     //['id','descrizione'];

    public $defaultOrderColumns = ['data_inizio' => 'ASC', ];
     //['cognome' => 'ASC','nome' => 'ASC'];

    public $columnsSearchAutoComplete = ['titolo'];
     //['cognome','denominazione','codicefiscale','partitaiva'];

    public $nItemsAutoComplete = 20;
    public $nItemsForSelectList = 100;
    public $itemNoneForSelectList = false;
    public $fieldsSeparator = ' | ';

    public function getCorsoFE() {

        return $this->titolo
            . ' - ' . $this->luogo . ' dal ' . FormatValues::formatDateIta($this->data_inizio)
            . ' al ' . FormatValues::formatDateIta($this->data_fine);
    }

    public function getPictureAttribute()
    {
        $foto = $this->fotos->first();
//        Log::info(print_r($foto,true));
        if ($foto) {
            return $foto->getUrl('orig');
        }
        return null;
    }

    public function getPictureAltAttribute()
    {
        $foto = $this->fotos->first();
        $alt = $this->titolo ?: "Foto principale";
//        Log::info(print_r($foto,true));
        if ($foto) {
            $alt = $foto->nome ?: $alt;
        }
        return $alt;
    }

    public function getPictureIconAttribute()
    {
        $foto = $this->fotos->first();
//        Log::info(print_r($foto,true));
        if ($foto) {
            return $foto->getUrl('iniziativaicon');
        }
        return '/imagecache/small/0';
    }

    public function postFormatSelectListDates($selectList) {

        foreach ($selectList as $key => $el) {
            $splitEl = explode(" | ",$el);
            $date1 = Arr::get($splitEl,2);
            $date2 = Arr::get($splitEl,3);
            try {
                $date1Obj = Carbon::createFromFormat('Y-m-d',$date1);
                $date1 = $date1Obj->format('d/m/Y');
            } catch (\Throwable $e) {

            }
            try {
                $date2Obj = Carbon::createFromFormat('Y-m-d',$date2);
                $date2 = $date2Obj->format('d/m/Y');
            } catch (\Throwable $e) {

            }
            $selectList[$key] = $splitEl[0] . ' - ' . $splitEl[1] . ' dal ' . $date1 . ($date2 ? (' al ' . $date2) : '');
        }

        asort($selectList);



        return $selectList;
    }

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom(['titolo','iniziativa_id'])
            ->saveSlugsTo('slug_it');
    }

    public function getRouteKeyName()
    {
        return 'slug_it';
    }

    public function save(array $options = [])
    {

        try {
            $saved = parent::save($options); // TODO: Change the autogenerated stub
        } catch (\Throwable $e) {
            if (Str::contains($e->getMessage(),"cor_slug_uq")) {
                throw new \Exception("I corsi di una iniziativa devono avere dei titoli univoci.");
            }
        }
        return $saved;
    }
}
