<?php

namespace App\Enums;

use Gecche\FSM\Contracts\FSMConfigInterface;
use Illuminate\Support\Arr;

enum ScuolaTipologiaGradoIstruzione: string
{
    use EnumHelperTrait;


case SCUOLA_SEC_SECONDO_GRADO_NON_STATALE = "SCUOLA SEC. SECONDO GRADO NON STATALE";
case LICEO_SCIENTIFICO = "LICEO SCIENTIFICO";
case ISTITUTO_COMPRENSIVO = "ISTITUTO COMPRENSIVO";
case LICEO_CLASSICO = "LICEO CLASSICO";
case ISTITUTO_SUPERIORE = "ISTITUTO SUPERIORE";
case IST_TECNICO_ECONOMICO_E_TECNOLOGICO = "IST TECNICO ECONOMICO E TECNOLOGICO";
case ISTITUTO_TECNICO_COMMERCIALE = "ISTITUTO TECNICO COMMERCIALE";
case IST_TEC_COMMERCIALE_E_PER_GEOMETRI = "IST TEC COMMERCIALE E PER GEOMETRI";
case IST_PROF_PER_I_SERVIZI_SOCIALI = "IST PROF PER I SERVIZI SOCIALI";
case IST_PROF_PER_I_SERVIZI_COMMERCIALI = "IST PROF PER I SERVIZI COMMERCIALI";
case ISTITUTO_MAGISTRALE = "ISTITUTO MAGISTRALE";
case IST_PROF_PER_LAGRICOLTURA_E_LAMBIENTE = "IST PROF PER L'AGRICOLTURA E L'AMBIENTE";
case IST_PROF_INDUSTRIA_E_ARTIGIANATO = "IST PROF INDUSTRIA E ARTIGIANATO";
case ISTITUTO_TECNICO_AGRARIO = "ISTITUTO TECNICO AGRARIO";
case IST_PROF_PER_I_SERVIZI_ALBERGHIERI_E_RISTORAZIONE = "IST PROF PER I SERVIZI ALBERGHIERI E RISTORAZIONE";
case LICEO_ARTISTICO = "LICEO ARTISTICO";
case ISTITUTO_TECNICO_INDUSTRIALE = "ISTITUTO TECNICO INDUSTRIALE";
case ISTITUTO_TECNICO_PER_GEOMETRI = "ISTITUTO TECNICO PER GEOMETRI";
case ISTITUTO_DARTE = "ISTITUTO D'ARTE";
case IST_PROF_PER_I_SERVIZI_COMMERCIALI_E_TURISTICI = "IST PROF PER I SERVIZI COMMERCIALI E TURISTICI";
case ISTITUTO_TECNICO_PER_ATTIVITA_SOCIALI_ITF = "ISTITUTO TECNICO PER ATTIVITA' SOCIALI (GIA' ITF)";
case IST_PROF_PER_LAGRICOLTURA = "IST PROF PER L'AGRICOLTURA";
case ISTITUTO_TECNICO_NAUTICO = "ISTITUTO TECNICO NAUTICO";
case ISTITUTO_TECNICO_AERONAUTICO = "ISTITUTO TECNICO AERONAUTICO";
case ISTITUTO_TECNICO_PER_IL_TURISMO = "ISTITUTO TECNICO PER IL TURISMO";
case IST_PROF_ALBERGHIERO = "IST PROF ALBERGHIERO";
case IST_PROF_INDUSTRIA_E_ATTIVITA_MARINARE = "IST PROF INDUSTRIA E ATTIVITA' MARINARE";
case IST_PROF_PER_I_SERVIZI_TURISTICI = "IST PROF PER I SERVIZI TURISTICI";
case SCUOLA_MAGISTRALE = "SCUOLA MAGISTRALE";
case IST_PROF_PER_I_SERVIZI_PUBBLICITARI = "IST PROF PER I SERVIZI PUBBLICITARI";
case IST_PROF_INDUSTRIA_E_ARTIGIANATO_PER_SORDOMUTI = "IST PROF INDUSTRIA E ARTIGIANATO PER SORDOMUTI";
case IST_PROF_INDUSTRIA_E_ARTIGIANATO_PER_CIECHI = "IST PROF INDUSTRIA E ARTIGIANATO PER CIECHI";
case IST_PROF_PER_I_SERVIZI_COMM_TUR_E_DELLA_PUBB = "IST PROF PER I SERVIZI COMM TUR E DELLA PUBB";
case IST_PROF_CINEMATOGRAFIA_E_TELEVISIONE = "IST PROF CINEMATOGRAFIA E TELEVISIONE";

    public static function getLangKey($case)
    {
        return 'enums.statuses.scuola_tipologia_grado_istruzione.' . $case->value;
    }

}

// see https://emekambah.medium.com/php-enum-and-use-cases-in-laravel-ac015cf181ad
