<?php

namespace App\Foorm\Candidato;


use App\Models\Corso;
use App\Models\Evento;
use App\Models\Iniziativa;
use App\Rules\CandidatoCodiceFiscale;
use App\Rules\CodiceFiscale;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

trait CandidatoTrait
{

    protected $validationCacheKey = 'candidatura.validation';

    public function setValidationSettings($input, $rules = null)
    {

        $validationCacheKey = $this->validationCacheKey;

        if (true || !Cache::has($validationCacheKey)) {
            $steps = Config::get('fe.candidatura.steps', []);
            $validation = [];
            foreach ($steps as $stepKey => $stepData) {
                $validation[$stepKey] = [];
                foreach (Arr::get($stepData, 'sections', []) as $sectionKey => $section) {
                    foreach (Arr::get($section, 'fields', []) as $fieldName => $fieldData) {
                        $validation[$stepKey][$fieldName] = Arr::get($fieldData, 'validation', []);
                    }
                }
            }
            Cache::forever($validationCacheKey, $validation);
        }

        $validationRules = Cache::get($validationCacheKey);

        $step = $this->step;

        if ($step) {
            $validationRules = Arr::get($validationRules,$step,[]);
        } else {
            $fullValidationRules = [];
            foreach (array_keys($validationRules) as $currStep) {
                $fullValidationRules = $fullValidationRules + $validationRules[$currStep];
            }
            $validationRules = $fullValidationRules;
        }

        if (array_key_exists('corsi',$validationRules)) {
            unset($validationRules['corsi']);
            $minCorsi = 2;
            $iniziativa = $this->model->iniziativa;
            if ($iniziativa) {
                $nCorsi = $iniziativa->corsi()->where('attivo',1)->get()->count();
                if ($nCorsi < 2) {
                    $minCorsi = 1;
                }
            }
            $validationRules['corsi-id'] = ['array','min:'.$minCorsi];
        }

        if (array_key_exists('voti',$validationRules)) {
            unset($validationRules['voti']);
            $validationRules['voti-id'] = ['array'];
            $validationRules['voti-materia_id.*'] = ['required'];
            $validationRules['voti-voto_anno_1.*'] = ['required','numeric','max:10'];
            $validationRules['voti-voto_anno_2.*'] = ['required','numeric','max:10'];
            $validationRules['voti-voto_primo_quadrimestre.*'] = ['required','numeric','max:10'];
        }

        $nazione = Arr::get($input,'nazione_id');
        if ($nazione) {
            // Assicuriamo che l'id del modello sia presente nell'input per la validazione del CF in edit
            $inputWithId = $input;
            if ($this->model && $this->model->exists) {
                $inputWithId['id'] = $this->model->getKey();
            }

            if ($nazione == 1) {
                $validationRules['codice_fiscale'] = ['required', new CodiceFiscale(), new CandidatoCodiceFiscale($inputWithId)];
                $validationRules['comune_id'] = ['required'];
                $validationRules['comune_estero'] = [];
            } else {
                $validationRules['codice_fiscale'] = [new CandidatoCodiceFiscale($inputWithId)];
                $validationRules['comune_estero'] = ['required'];
                $validationRules['comune_id'] = [];
            }
        }

        $this->validationSettings['rules'] = $validationRules;

//        Log::info("VALIDATION RULES");
//
//        Log::info($this->validationSettings['rules']);
//        Log::info($this->step);

    }


    protected function setFieldsToModel($model, $configFields, $input)
    {
        unset($input['provincia_scuola_id']);

        // Campi array che devono essere impostati a null se non presenti nell'input
        // (checkbox non spuntati non vengono trasmessi dal browser)
        $arrayFields = ['stages', 'gare_internazionali', 'gare_umanistiche'];

        foreach ($arrayFields as $fieldName) {
            if (array_key_exists($fieldName, $configFields) && !array_key_exists($fieldName, $input)) {
                $input[$fieldName] = null;
            }
        }

        parent::setFieldsToModel($model, $configFields, $input);
    }



    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->step = Arr::get($this->input,'step');
        $this->autosave = Arr::get($this->input,'autosave');
    }


    protected
    function saveRelated($input)
    {

        foreach ($this->belongsTos as $belongsToKey => $belongsToValue) {
            $saveRelatedName = 'saveRelated' . Str::studly($belongsToKey);
            $belongsToType = $belongsToValue['relationType'];
            $saveParams = $this->getRelationConfig($belongsToKey, 'saveParams', []);
            $this->$saveRelatedName($belongsToType, $belongsToKey, $belongsToValue, $input, $saveParams);
        }


        foreach ($this->hasManies as $hasManyKey => $hasManyValue) {
            if ($this->step) {
                $stepValidationRules = Arr::get(Cache::get($this->validationCacheKey,[]),$this->step,[]);
                if (!array_key_exists($hasManyKey,$stepValidationRules)) {
                    continue;
                }
            }
            $saveRelatedName = 'saveRelated' . Str::studly($hasManyKey);
            $hasManyType = $hasManyValue['relationType'];
            $saveType = $this->getRelationConfig($hasManyKey, 'saveType');
            $saveParams = $this->getRelationConfig($hasManyKey, 'saveParams', []);

            if ($saveType) {
                $hasManyType = $hasManyType . Str::studly($saveType);
            }

            $hasManyInputs = $this->getHasManyInputs($hasManyKey,$input);
            $this->$saveRelatedName($hasManyType, $hasManyKey, $hasManyValue, $hasManyInputs, $saveParams);
        }
    }

    protected function saveModel($input)
    {
        if ($this->step) {
            $this->model->addStepToInfo($this->step);
        }
        return parent::saveModel($input); // TODO: Change the autogenerated stub
    }

    public function save($input = null, $validate = true)
    {
        $saved = parent::save($input, $validate); // TODO: Change the autogenerated stub

        if ($saved) {
            $this->model->calculateMedia(true);
        }
        return $saved;
    }

    public function createOptionsCorsi($fieldValue,$defaultOptionsValues,$relationName = null,$relationMetadata = []) {

        Log::info("HERE CORSI " . $this->model->iniziativa_id);
        $corso = new Corso();
        if (!$this->model->iniziativa) {
            return $corso->getForSelectList(null,null,[],null,'dates');
        }

        return $corso->getForSelectList($corso->where('iniziativa_id',$this->model->iniziativa_id)->where('attivo',1),null,[],null,'dates');

    }


}
